version: '3'
services:
  app:
    container_name: apache-server
    restart: always
    build: .
    ports:
      - '8080:80'
    volumes: ['./:/var/www/html']
    
  mysql:
    container_name: mysql
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: 'db'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'root'
      # You can use whatever password you like
      MYSQL_PASSWORD: '12345678'
      # Password for root access
      MYSQL_ROOT_PASSWORD: '12345678'
    ports:
      - '3306:3306'
    networks:
      - aicte
    
  phpmyadmin:
    depends_on:
      - mysql
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '8081:80'
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: '12345678'
    networks:
      - aicte

networks:
  aicte:
volumes:
  db_data: